# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
