# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_auto_20161228_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Collection'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
