# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-18 18:08
from __future__ import unicode_literals

import collection.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_auto_20170302_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='link',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(code='Invalid key', message='Must be an Etsy item listing link', regex='^http(s)?://(www\\.)?etsy\\.com/uk/listing/[0-9]+(/[a-z-]+)?$'), collection.validators.validate_link_exists]),
        ),
    ]
